- name: restart mysql
  service:
    name: mysql
    state: restarted

# - name: restart mysql exporter
#   service:
#     name: prometheus-mysqld-exporter
#     state: restarted
#     enabled: true

- name: Reset MySQL source
  community.mysql.mysql_replication:
    mode: "{{ item }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  loop:
    - stopreplica
    - resetprimary
  when: inventory_hostname == mysql_host

- name: Reset MySQL replica
  community.mysql.mysql_replication:
    mode: "{{ item }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    master_host: "{{ mysql_host }}"
    master_user: "{{ mysql_replication_user }}"
    master_password: "{{ mysql_replication_password }}"
  loop:
    - stopreplica
    - changeprimary
    - resetreplica
    - startreplica
  when: inventory_hostname != mysql_host


#Exporter

- name: restart mysql exporter
  service:
    name: prometheus-mysqld-exporter
    state: restarted
    enabled: true