version: '3'
services:
  app:
    image: floppax/web-app-automation
    ports:
      - 8001:8001
    volumes:
      - ./app:/app
    env_file:
      - .env.app
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - db_data:/home/orest/Documents/app/db_data
    env_file:
      - .env.db
    networks:
      - app-network
volumes:
  db_data:


networks:
  app-network:
    driver: bridge