---
- name: Update APT cache
  ansible.builtin.apt:
    cache_valid_time: 86400

- name: Install prometheus node exporter
  apt:
    name: prometheus-node-exporter

- name: Copy prometheus node exporter config
  template:
    src: prometheus-node-exporter.service.j2
    dest: /etc/systemd/system/prometheus-node-exporter.service
  notify: restart prometheus-node-exporter