{
 "title": "Main",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes) / 1024 / 1024 / 1024 \n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU load",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((sum(irate(node_cpu_seconds_total {mode!=\"idle\"} [1m])) by (instance)) / sum(irate(node_cpu_seconds_total[1m])) by (instance)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HAProxy 1 Status ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "haproxy_up{instance=\"vm-1:9101\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Keepalived 1 Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "keepalived_up{instance=\"vm-1:9115\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Keepalived 1 State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "keepalived_vrrp_state{instance=\"vm-1:9115\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HAProxy 1",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "haproxy_server_up{instance=\"vm-1:9101\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DNS Queries per minute",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "rate(bind_resolver_queries_total{type=\"A\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MySQL SELECT per minute",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"select\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HAProxy 2 Status ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "haproxy_up{instance=\"vm-2:9101\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Keepalived 2 Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "keepalived_up{instance=\"vm-2:9115\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Keepalived 2 State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "keepalived_vrrp_state{instance=\"vm-2:9115\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HAProxy 2",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "haproxy_server_up{instance=\"vm-2:9101\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DNS 1 Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bind_up{instance=\"vm-1:9119\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DNS 2 Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bind_up{instance=\"vm-2:9119\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MySQL 1 Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_up{instance=\"vm-1:9104\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MySQL 2 Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_up{instance=\"vm-2:9104\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Web Server 1 Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_up{instance=\"vm-1:9113\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NGINX Requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}