- name: Install prometheus
  ansible.builtin.apt:
    name: prometheus

- name: Copy prometheus config
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
  notify: restart prometheus

- name: Copy prometheus service file
  ansible.builtin.template:
    src: prometheus.service.j2
    dest: /etc/default/prometheus
  notify: restart prometheus

- name: Start prometheus
  ansible.builtin.service:
    name: prometheus
    state: started
    enabled: true

#Add CNAME record for Prometheus
- name: Add CNAME records for Prometheus
  community.general.nsupdate:
    zone: "domain.cool"
    record: "prometheus"
    value: "{{ inventory_hostname }}"
    type: "CNAME"
    key_algorithm: "hmac-sha256"
    server: "{{ hostvars[groups['dns_primary'][0]]['ansible_default_ipv4']['address'] }}"
    key_name: "update.key" 
    key_secret: "{{update_key}}" 
  no_log: true