apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-configmap
data:
  grafana.ini: |
    [server]
    domain = prometheus.test.com
    root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana/
    serve_from_sub_path = true