apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-ds-configmap
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      orgId: 1
      url: http://prometheus-service:9090/prometheus
      basicAuth: false
      isDefault: true
      editable: true

   
