apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-node-exporter
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "9100"
  labels:
    app: prometheus-node-exporter
spec:
  selector:
    matchLabels:
      app: prometheus-node-exporter
  template:
    metadata:
      labels:
        app: prometheus-node-exporter
    spec:
      containers:
      - name: prometheus-node-exporter
        image: quay.io/prometheus/node-exporter:latest
        ports:
        - containerPort: 9100
      hostNetwork: true
      hostPID: true
      hostIPC: true
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-node-exporter
spec:
  type: NodePort
  selector:
    app: prometheus-node-exporter
  ports:
  - protocol: TCP
    port: 9100
    targetPort: 9100
    name: "metrics"
